Recipe set
WildCodeSchool/hackmasters-project-backend pull request #13
Opened 2023-07-17 14:29 UTC by remy-rm

2023-07-19 08:42 UTC, td6904 approved these changes

2023-07-19 12:48 UTC, Benja-san requested changes

2023-07-19 12:48 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/RecipeController.java
> +    public ResponseEntity<List<Recipe>> searchRecipesByPartialName(@RequestParam("recipeName") String recipeName) {
some issues could occur if you're using the recipeName as pathVariable (accents, spaces, special characters) use a slug instead

2023-07-19 12:48 UTC, Benja-san commented on src/main/java/com/templateproject/api/controller/RecipeController.java
> +    @GetMapping("/country")
same for all researches by name, it's safer to use a slugified name

2023-07-20 08:08 UTC, Benja-san approved these changes

2023-07-20 08:20 UTC, merged